MERGE [dbo].[createRequest_level2] AS target
USING [hlp].[createRequest_level2] AS source
ON target.[AppId] = source.[AppId]

WHEN MATCHED THEN
    UPDATE SET
        target.[Customer] = source.[Customer],
        target.[CustomerType] = source.[CustomerType],
        target.[Type] = source.[Type],
        target.[ID] = source.[ID],
        target.[CaseID] = source.[CaseID],
        target.[Concentrated] = source.[Concentrated],
        target.[ContactFirstName] = source.[ContactFirstName],
        target.[ContactLastName] = source.[ContactLastName],
        target.[ContactID] = source.[ContactID],
        target.[ContactCell] = source.[ContactCell],
        target.[ContactEmail] = source.[ContactEmail],
        target.[ApprovedSign] = source.[ApprovedSign],
        target.[Nearness] = source.[Nearness],
        target.[Dropping] = source.[Dropping],
        target.[SubFrequency] = source.[SubFrequency],
        target.[Diesel] = source.[Diesel],
        target.[Generator] = source.[Generator],
        target.[Neto] = source.[Neto],
        target.[Social] = source.[Social],
        target.[subParent] = source.[subParent],
        target.[sonMeters] = source.[sonMeters],
        target.[HistoricalDistributorID] = source.[HistoricalDistributorID],
        target.[Private] = source.[Private],
        target.[SupplierDeclaration] = source.[SupplierDeclaration],
        target.[POASignatureDate] = source.[POASignatureDate],
        target.[POASignatureTime] = source.[POASignatureTime],
        target.[OldContarctNum] = source.[OldContarctNum],
        target.[Meters] = source.[Meters],
        target.[EDJustifiableReason] = source.[EDJustifiableReason],
        target.[CreatedDate] = source.[CreatedDate],
        target.[successRecords] = source.[successRecords],
        target.[responseObj] = source.[responseObj],
        target.[isSuccess] = source.[isSuccess],
        target.[failedRecords] = source.[failedRecords],
        target.[message] = source.[message]

WHEN NOT MATCHED BY TARGET THEN
    INSERT (
        [AppId],
        [Customer],
        [CustomerType],
        [Type],
        [ID],
        [CaseID],
        [Concentrated],
        [ContactFirstName],
        [ContactLastName],
        [ContactID],
        [ContactCell],
        [ContactEmail],
        [ApprovedSign],
        [Nearness],
        [Dropping],
        [SubFrequency],
        [Diesel],
        [Generator],
        [Neto],
        [Social],
        [subParent],
        [sonMeters],
        [HistoricalDistributorID],
        [Private],
        [SupplierDeclaration],
        [POASignatureDate],
        [POASignatureTime],
        [OldContarctNum],
        [Meters],
        [EDJustifiableReason],
        [CreatedDate],
        [successRecords],
        [responseObj],
        [isSuccess],
        [failedRecords],
        [message]
    )
    VALUES (
        source.[AppId],
        source.[Customer],
        source.[CustomerType],
        source.[Type],
        source.[ID],
        source.[CaseID],
        source.[Concentrated],
        source.[ContactFirstName],
        source.[ContactLastName],
        source.[ContactID],
        source.[ContactCell],
        source.[ContactEmail],
        source.[ApprovedSign],
        source.[Nearness],
        source.[Dropping],
        source.[SubFrequency],
        source.[Diesel],
        source.[Generator],
        source.[Neto],
        source.[Social],
        source.[subParent],
        source.[sonMeters],
        source.[HistoricalDistributorID],
        source.[Private],
        source.[SupplierDeclaration],
        source.[POASignatureDate],
        source.[POASignatureTime],
        source.[OldContarctNum],
        source.[Meters],
        source.[EDJustifiableReason],
        source.[CreatedDate],
        source.[successRecords],
        source.[responseObj],
        source.[isSuccess],
        source.[failedRecords],
        source.[message]
    );
